[project]
name = "speaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bleak>=2.1.1",
    "numpy>=2.2.6",
    "pydub>=0.25.1",
    "sounddevice>=0.5.5",
]
